$desiredPackages = [
  'ant',
  'bison',
  'clusterssh',
  'curl',
  'dconf-tools',
  'dstat',
  'eclipse',
  'eclipse-jdt',
  'erlang-nox',
  'expect',
  'git',
  'git-core',
  'gitg',
  'gnome-do',
  'htop',
  'iftop',
  'jnettop',
  'libaio1',
  'libffi-dev',
  'libgdbm-dev',
  'libgtk-3-dev',
  'libgtk2.0-dev',
  'libjpeg62',
  'libreadline6-dev',
  'libsqlite3-dev',
  'libssl-dev',
  'libxml2-dev',
  'libxslt1-dev',
  'libyaml-dev',
  'maven',
  'meld',
  'ncurses-term',
  'nmap',
  'ntp',
  'openjdk-6-jdk',
  'python',
  'rar',
  'screen',
  'sqlite3',
  'sshfs',
  'subversion',
  'subversion-tools',
  'sysstat',
  'terminator',
  'tmux',
  'unrar',
  'unzip',
  'xclip',
  'zlib1g-dev',
#  'ack-grep',
#  'build-essential',
#  'gedit',
#  'gedit-plugins',
#  'msttcorefonts',
#  'ubuntu-restricted-extras',
]

package { $desiredPackages:
  ensure => installed
}

$undesiredPackages = ['avahi-daemon']

package { $undesiredPackages:
  ensure => purged
}
